---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  enabled: false
platforms:
  - name: instance
    box: centos/7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
scenario:
  name: vagrant
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: false
